var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(auth)/forgot-password/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e6a8087._.js")
R.c("server/chunks/ssr/node_modules_next_c6b66f8c._.js")
R.c("server/chunks/ssr/node_modules_bd1d7c1f._.js")
R.c("server/chunks/ssr/src_app_ca777385._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a9f7d8d7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_app_(auth)_layout_tsx_92f1b6d4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__2570ecb0._.js")
R.c("server/chunks/ssr/_a2985d5b._.js")
R.c("server/chunks/ssr/_b514a275._.js")
R.m(32897)
R.m(55725)
module.exports=R.m(55725).exports
