var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/preprocessing/route.js")
R.c("server/chunks/[root-of-the-server]__6352e9a9._.js")
R.c("server/chunks/[root-of-the-server]__05773d8b._.js")
R.c("server/chunks/node_modules_next_d739b5ba._.js")
R.c("server/chunks/[root-of-the-server]__9c93a9f3._.js")
R.c("server/chunks/[root-of-the-server]__595db740._.js")
R.c("server/chunks/[root-of-the-server]__434ff35f._.js")
R.m(84448)
R.m(51516)
module.exports=R.m(51516).exports
