// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/forgot-password" | "/home" | "/login" | "/mood" | "/mypage" | "/mypage/inquiry" | "/mypage/privacy" | "/mypage/qna" | "/register"
type AppRouteHandlerRoutes = "/api/ai/background-params" | "/api/ai/chat" | "/api/auth/[...nextauth]" | "/api/auth/account" | "/api/auth/forgot-password" | "/api/auth/profile" | "/api/auth/register" | "/api/auth/reset-password" | "/api/auth/survey-skip" | "/api/auth/survey-status" | "/api/auth/verify-reset-code" | "/api/devices" | "/api/devices/[deviceId]" | "/api/devices/[deviceId]/name" | "/api/devices/[deviceId]/power" | "/api/devices/[deviceId]/scent-interval" | "/api/devices/[deviceId]/scent-level" | "/api/inquiry" | "/api/moods" | "/api/moods/current" | "/api/moods/current/color" | "/api/moods/current/generate" | "/api/moods/current/refresh" | "/api/moods/current/scent" | "/api/moods/current/song" | "/api/moods/preference" | "/api/moods/saved" | "/api/moods/saved/[savedMoodId]" | "/api/preferences" | "/api/preprocessing" | "/api/sleep/generate" | "/api/sleep/today"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ai/background-params": {}
  "/api/ai/chat": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/account": {}
  "/api/auth/forgot-password": {}
  "/api/auth/profile": {}
  "/api/auth/register": {}
  "/api/auth/reset-password": {}
  "/api/auth/survey-skip": {}
  "/api/auth/survey-status": {}
  "/api/auth/verify-reset-code": {}
  "/api/devices": {}
  "/api/devices/[deviceId]": { "deviceId": string; }
  "/api/devices/[deviceId]/name": { "deviceId": string; }
  "/api/devices/[deviceId]/power": { "deviceId": string; }
  "/api/devices/[deviceId]/scent-interval": { "deviceId": string; }
  "/api/devices/[deviceId]/scent-level": { "deviceId": string; }
  "/api/inquiry": {}
  "/api/moods": {}
  "/api/moods/current": {}
  "/api/moods/current/color": {}
  "/api/moods/current/generate": {}
  "/api/moods/current/refresh": {}
  "/api/moods/current/scent": {}
  "/api/moods/current/song": {}
  "/api/moods/preference": {}
  "/api/moods/saved": {}
  "/api/moods/saved/[savedMoodId]": { "savedMoodId": string; }
  "/api/preferences": {}
  "/api/preprocessing": {}
  "/api/sleep/generate": {}
  "/api/sleep/today": {}
  "/forgot-password": {}
  "/home": {}
  "/login": {}
  "/mood": {}
  "/mypage": {}
  "/mypage/inquiry": {}
  "/mypage/privacy": {}
  "/mypage/qna": {}
  "/register": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
