// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../src/app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../src/app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../src/app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/(main)/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home">> = Specific
  const handler = {} as typeof import("../src/app/(main)/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/(main)/mood/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mood">> = Specific
  const handler = {} as typeof import("../src/app/(main)/mood/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/(main)/mypage/inquiry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage/inquiry">> = Specific
  const handler = {} as typeof import("../src/app/(main)/mypage/inquiry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/(main)/mypage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage">> = Specific
  const handler = {} as typeof import("../src/app/(main)/mypage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/(main)/mypage/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage/privacy">> = Specific
  const handler = {} as typeof import("../src/app/(main)/mypage/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/(main)/mypage/qna/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage/qna">> = Specific
  const handler = {} as typeof import("../src/app/(main)/mypage/qna/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/ai/background-params/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/background-params">> = Specific
  const handler = {} as typeof import("../src/app/api/ai/background-params/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/ai/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/chat">> = Specific
  const handler = {} as typeof import("../src/app/api/ai/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/auth/account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/account">> = Specific
  const handler = {} as typeof import("../src/app/api/auth/account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../src/app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/auth/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/profile">> = Specific
  const handler = {} as typeof import("../src/app/api/auth/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/auth/survey-skip/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/survey-skip">> = Specific
  const handler = {} as typeof import("../src/app/api/auth/survey-skip/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/auth/survey-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/survey-status">> = Specific
  const handler = {} as typeof import("../src/app/api/auth/survey-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/auth/verify-reset-code/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-reset-code">> = Specific
  const handler = {} as typeof import("../src/app/api/auth/verify-reset-code/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/devices/[deviceId]/name/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/devices/[deviceId]/name">> = Specific
  const handler = {} as typeof import("../src/app/api/devices/[deviceId]/name/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/devices/[deviceId]/power/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/devices/[deviceId]/power">> = Specific
  const handler = {} as typeof import("../src/app/api/devices/[deviceId]/power/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/devices/[deviceId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/devices/[deviceId]">> = Specific
  const handler = {} as typeof import("../src/app/api/devices/[deviceId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/devices/[deviceId]/scent-interval/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/devices/[deviceId]/scent-interval">> = Specific
  const handler = {} as typeof import("../src/app/api/devices/[deviceId]/scent-interval/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/devices/[deviceId]/scent-level/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/devices/[deviceId]/scent-level">> = Specific
  const handler = {} as typeof import("../src/app/api/devices/[deviceId]/scent-level/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/devices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/devices">> = Specific
  const handler = {} as typeof import("../src/app/api/devices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/inquiry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inquiry">> = Specific
  const handler = {} as typeof import("../src/app/api/inquiry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/moods/current/color/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moods/current/color">> = Specific
  const handler = {} as typeof import("../src/app/api/moods/current/color/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/moods/current/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moods/current/generate">> = Specific
  const handler = {} as typeof import("../src/app/api/moods/current/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/moods/current/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moods/current/refresh">> = Specific
  const handler = {} as typeof import("../src/app/api/moods/current/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/moods/current/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moods/current">> = Specific
  const handler = {} as typeof import("../src/app/api/moods/current/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/moods/current/scent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moods/current/scent">> = Specific
  const handler = {} as typeof import("../src/app/api/moods/current/scent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/moods/current/song/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moods/current/song">> = Specific
  const handler = {} as typeof import("../src/app/api/moods/current/song/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/moods/preference/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moods/preference">> = Specific
  const handler = {} as typeof import("../src/app/api/moods/preference/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/moods/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moods">> = Specific
  const handler = {} as typeof import("../src/app/api/moods/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/moods/saved/[savedMoodId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moods/saved/[savedMoodId]">> = Specific
  const handler = {} as typeof import("../src/app/api/moods/saved/[savedMoodId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/moods/saved/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moods/saved">> = Specific
  const handler = {} as typeof import("../src/app/api/moods/saved/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preferences">> = Specific
  const handler = {} as typeof import("../src/app/api/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/preprocessing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preprocessing">> = Specific
  const handler = {} as typeof import("../src/app/api/preprocessing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/sleep/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sleep/generate">> = Specific
  const handler = {} as typeof import("../src/app/api/sleep/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/api/sleep/today/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sleep/today">> = Specific
  const handler = {} as typeof import("../src/app/api/sleep/today/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
